### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mjgarton** [ybubnov/go-uuid#5]
If this is derived from Linux kernel code then you need to comply with the license which is GPL V2. Releasing as MIT is a voilation of the original license terms. (I am not a lawyer but I understand a bit about various floss licenses)

**Comment by mjgarton** [comment]
If you are simply calling the kernel this doesn't apply of course. (I haven't inspected your implementation)

**Comment by weatherglass** [comment]
@mjgarton If you read the code, it uses the proc virtual system to get the uuids from the kernel.

**Comment by mjgarton** [comment]
In that case, I don't think there is a problem.  Sorry for the noise.
